[package]
name = "siralim-building"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version = "0.20.0", features = [ "csr" ] }
log = "0.4.17"
wasm-logger = "0.2.0"
rust-embed = { version = "6.4.2", features = [ "debug-embed" ] }
serde = "1.0.152"
serde_json = "1.0.93"