[package]
name = "gen"
version = "0.1.0"

[dependencies]
data = { path = "../data" }
reqwest = { version = "0.11.14", features = [ "blocking" ] }
csv = "1.2.0"
serde = { version = "1.0.152", features = [ "derive" ] }
