[package]
name = "gen"
version = "0.1.0"

[dependencies]
data = { path = "../data" }
reqwest = { version = "0.11.14", features = [ "blocking" ] }
csv = "1.1.6"
serde = { version = "1.0.152", features = [ "derive" ] }
apache-avro = { version = "0.14.0", features = [ "derive" ] }
tantivy = "0.19.2"