name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Install trunk
        uses: baptiste0928/cargo-install@v2
        with:
          crate: trunk

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install npm dependencies
        run: npm ci

      - name: Setup Pages
        id: setup-pages
        uses: actions/configure-pages@v3

      - name: Build
        run: trunk build --release --public-url ${{ steps.setup-pages.outputs.base_path }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist

  deploy:
    needs: [build]
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
